### ISSUE TITLE
Analysed assembly must be compiled in Release mode

### ISSUE THREAD

**Issue by kfrajtak** [dnWalker-project/dnWalker#5]
Analysis fails on code with `>=` when condition evaluates as true, `<=`, `!=` in both cases.

`Branch_LowerThanOrEquals` compiled in debug mode - `x <= 5`, `x = 6`
```
IL_0000: nop
// if (x <= 5)
IL_0001: ldarg.0
IL_0002: ldc.i4.5
IL_0003: cgt      0 on stack, constraint x > 5
// (no C# code)
IL_0005: ldc.i4.0 
IL_0006: ceq    1 != 0, 0 on stack, constraint Not(x > 5)
IL_0008: stloc.0
IL_0009: ldloc.0
IL_000a: brfalse.s IL_0020
```

Path constraint is `Not(x > 5)` which is not correct since `x = 6`.

`Branch_LowerThanOrEquals` compiled in release mode
```
// if (x <= 5)
IL_0000: ldarg.0
IL_0001: ldc.i4.5
IL_0002: bgt.s IL_0014
```

Only assemblies compiled in release mode should be analysed otherwise an exception should be thrown.

**Comment by benjamin-hejl** [comment]
solved way back
